import tiposDeSimbolos from '../tipos-de-simbolos/lexico-regular';

export const palavrasReservadas = {
    a: tiposDeSimbolos.A,
    ai: tiposDeSimbolos.AI,
    ajuda: tiposDeSimbolos.AJUDA,
    bambam: tiposDeSimbolos.BAMBAM,
    birl: tiposDeSimbolos.BIRL,
    bora: tiposDeSimbolos.BORA,
    biceps: tiposDeSimbolos.BICEPS,
    ce: tiposDeSimbolos.CE,
    cumpade: tiposDeSimbolos.CUMPADE,
    da: tiposDeSimbolos.DA,
    dar: tiposDeSimbolos.DAR,
    do: tiposDeSimbolos.DO,
    doente: tiposDeSimbolos.DOENTE,
    descendente: tiposDeSimbolos.DESCENDENTE,
    ele: tiposDeSimbolos.ELE,
    essa: tiposDeSimbolos.ESSA,
    filho: tiposDeSimbolos.FILHO,
    frango: tiposDeSimbolos.FRANGO,
    gente: tiposDeSimbolos.GENTE,
    home: tiposDeSimbolos.HOME,
    hora: tiposDeSimbolos.HORA,
    mais: tiposDeSimbolos.MAIS,
    maluco: tiposDeSimbolos.MALUCO,
    monstrao: tiposDeSimbolos.MONSTRAO,
    monstro: tiposDeSimbolos.MONSTRO,
    monstrinho: tiposDeSimbolos.MONSTRINHO, // Essa palavra reservada faz referencia a um short int que em C tem 2bytes ou 16 bits, mas não tratamos ela assim, aqui ela é ignorada e a tratamos como um inteiros de 4 bytes ou 32 bits.
    nao: tiposDeSimbolos.NAO,
    negativa: tiposDeSimbolos.NEGATIVA,
    o: tiposDeSimbolos.O,
    oh: tiposDeSimbolos.OH,
    po: tiposDeSimbolos.PO,
    porra: tiposDeSimbolos.PORRA,
    puta: tiposDeSimbolos.PUTA,
    que: tiposDeSimbolos.QUE,
    quer: tiposDeSimbolos.QUER,
    quero: tiposDeSimbolos.QUERO,
    sai: tiposDeSimbolos.SAI,
    show: tiposDeSimbolos.SHOW,
    ta: tiposDeSimbolos.TA,
    vai: tiposDeSimbolos.VAI,
    vamo: tiposDeSimbolos.VAMO,
    ver: tiposDeSimbolos.VER,
    trapezio: tiposDeSimbolos.TRAPEZIO,
};
